/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hernan
 */
public class Fondos extends javax.swing.JDialog {

    /**
     * Creates new form Fondos
     */
    public Fondos(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        this.buttonGroup1.add(jRadioButton1);
        this.buttonGroup1.add(jRadioButton2);
        this.buttonGroup1.add(jRadioButton3);
        this.buttonGroup1.add(jRadioButton4);
        this.buttonGroup1.add(jRadioButton5);
        conf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fondos");

        jRadioButton1.setText("Fondo1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Fondo 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Fondo 3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Fondo 4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Sin fondo");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/chgfgfgeck.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        FileOutputStream out = null;
        Properties p = new Properties();
        try {
            p.load(new FileInputStream("conf.ini"));
        } catch (IOException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setProperty("Fondo", "cats2.jpg");
        try {
            out = new FileOutputStream("conf.ini");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.save(out, "/* properties updated */");
        this.jRadioButton2.setSelected(false);
        this.jRadioButton3.setSelected(false);
        this.jRadioButton4.setSelected(false);
        this.jRadioButton5.setSelected(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/cats22.jpg"))); // NOI18N
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        FileOutputStream out = null;
        Properties p = new Properties();
        try {
            p.load(new FileInputStream("conf.ini"));
        } catch (IOException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setProperty("Fondo", "gatos.jpg");
        try {
            out = new FileOutputStream("conf.ini");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.save(out, "/* properties updated */");
        this.jRadioButton1.setSelected(false);
        this.jRadioButton3.setSelected(false);
        this.jRadioButton4.setSelected(false);
        this.jRadioButton5.setSelected(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/gatos2.jpg"))); // NOI18N
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        FileOutputStream out = null;
        Properties p = new Properties();
        try {
            p.load(new FileInputStream("conf.ini"));
        } catch (IOException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setProperty("Fondo", "cutedog.jpg");
        try {
            out = new FileOutputStream("conf.ini");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.save(out, "/* properties updated */");
        this.jRadioButton1.setSelected(false);
        this.jRadioButton2.setSelected(false);
        this.jRadioButton4.setSelected(false);
        this.jRadioButton5.setSelected(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/cutedog2.jpg")));
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        FileOutputStream out = null;
        Properties p = new Properties();
        try {
            p.load(new FileInputStream("conf.ini"));
        } catch (IOException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setProperty("Fondo", "perros.jpg");
        try {
            out = new FileOutputStream("conf.ini");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.save(out, "/* properties updated */");
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/perros2.jpg")));
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        FileOutputStream out = null;
        Properties p = new Properties();
        try {
            p.load(new FileInputStream("conf.ini"));
        } catch (IOException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setProperty("Fondo", "nada");
        try {
            out = new FileOutputStream("conf.ini");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.save(out, "/* properties updated */");
        jLabel1.setIcon(null);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Fondos dialog = null;
                try {
                    dialog = new Fondos(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(Fondos.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
 private String fondo = "";
 
    public void conf() throws IOException {

        Properties p = new Properties();
        p.load(new FileInputStream("conf.ini"));
        fondo = p.getProperty("Fondo");
        // switch con fondo chico y selects de radio butons

        if (fondo.equals("cats2.jpg")) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/" + "cats22.jpg")));
            this.jRadioButton1.setSelected(true);
        }
        if (fondo.equals("gatos.jpg")) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/" + "gatos2.jpg")));
            this.jRadioButton2.setSelected(true);
        }
        if (fondo.equals("cutedog.jpg")) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/" + "cutedog2.jpg")));
            this.jRadioButton3.setSelected(true);
        }
        if (fondo.equals("perros.jpg")) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/" + "perros2.jpg")));
            this.jRadioButton4.setSelected(true);
        }
        if (fondo.equals("nada")) {
            jLabel1.setIcon(null);
            this.jRadioButton5.setSelected(true);
        }




    }
}
